banking_system/about/routes.py
from flask import render_template
from flask import Blueprint

about = Blueprint('about', __name__)


@about.route("/money")
def money():
    """ render the money.html template to show static data """

    return render_template('money.html', title='money')


@about.route("/fixed-deposits")
def fd():
    """ render the fd.html template to show static data """

    return render_template('fd.html', title='fixed-deposits')


@about.route("/loan")
def loan():
    """ render the loan.html template to show static data """

    return render_template('loan.html', title='loan')


@about.route("/insurance")
def insurance():
    """ render the insurance.html template to show static data """

    return render_template('insurance.html', title='insurance')

banking_system/admin/routes.py
from flask import render_template, url_for, flash, redirect, request, jsonify, Blueprint
from flask_login import login_user, login_required
from banking_system import db, bcrypt
from banking_system.admin.utils import authentication_req, add_loan_money_to_user, save_picture_about
from banking_system.models import Atm, User, Branch, BankDetails, Account, Loan, LoanType, Insurance, InsuranceType, \
    FixedDeposit, BankMember, MemberRole, LoanDetails, InsuranceDetails
from banking_system.admin.forms import AddBranch, LoginForm, AddAtm, UserAccountStatus, LoanApprovalStatus, \
    InsuranceApprovalForm, BankMemberData, UpdateFdStatus, AddMemberRole, LoanChoice, InsuranceChoice
from banking_system.admin.constants import ADMIN_LOGIN_SUCCESS, FLASH_MESSAGES, ADMIN_LOGIN_UNSUCCESS, USER_DELETED, \
    BRANCH_EXISTED, BRANCH_ADDED, ATM_EXISTED, ATM_ADDED, BANK_MEMBER_DELETED, BANK_MEMBER_ADDED, \
    STATUS_UPDATE, ROLE_ALREADY_EXIST, NEW_ROLE_ADDED, LOAN_CHOICE_ALREADY_EXIST, NEW_LOAN_CHOICE_ADDED, \
    INSURANCE_CHOICE_ALREADY_EXIST, NEW_INSURANCE_CHOICE_ADDED, NO_RECORD_ACTIVITY, NO_USER_FOUND, NOT_VALID_PICTURE, \
    BRANCH_DELETED, BRANCH_IS_ASSOCIATED, ATM_DELETED, ROLE_DELETED, ROLE_IS_OCCUPIED, LOAN_CHOICE_DELETED, \
    LOAN_CHOICE_IS_OCCUPIED, INSURANCE_CHOICE_DELETED, INSURANCE_CHOICE_IS_OCCUPIED

admin = Blueprint('admin', __name__)


@admin.route("/admin-login/", methods=['GET', 'POST'])
def admin_login():
    """
        For admin login
        [ only admin can have the authority to login by using this ]
        form: LoginForm
        template: admin_login.html [ for LoginForm ]
                  admin_dashboard.html [ after login ]
        redirects to:
            after successfully login: admin_dashboard.html [ template ]
    """
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(user_email='steffy.inexture@gmail.com').first()
        if user is not None and form.user_password.data == user.user_password:
            login_user(user, remember=form.remember.data)
            flash(ADMIN_LOGIN_SUCCESS, FLASH_MESSAGES['SUCCESS'])
            users = User.query.order_by(User.user_id.desc())
            atms = Atm.query.order_by(Atm.atm_id.desc())
            branchs = Branch.query.order_by(Branch.branch_id.desc())
            return render_template('admin_dashboard.html', users=users, branchs=branchs, atms=atms)
        else:
            flash(ADMIN_LOGIN_UNSUCCESS, FLASH_MESSAGES['FAIL'])
    return render_template('admin_login.html', title='login', form=form)


@admin.route("/admin/admin_dashboard/", methods=['GET', 'POST'])
@login_required
@authentication_req
def admin_dashboard():
    """
        Admin dashboard shows the option functionalities which is performed by the bank admin only
        template/redirects to: admin_dashboard.html
        params:
            users = All user data
            branchs = All branches data of the bank
            atms = All atms data of the bank
            accounts = All accounts data of the bank
    """
    users = User.query.all()
    accounts = Account.query.all()
    atms = Atm.query.order_by(Atm.atm_id.desc())
    branchs = Branch.query.order_by(Branch.branch_id.desc())
    return render_template('admin_dashboard.html', users=users, branchs=branchs, atms=atms, accounts=accounts)


@admin.route("/all-user-data/", methods=['GET', 'POST'])
@login_required
@authentication_req
def admin_user_data():
    """
        Shows all the bank users with its status [ Active / Inactive ]
        template / redirects to: admin_user_data.html
        params:
            page = for pagination purpose
            per_page = number of rows shown in one-page
            users = all bank user data [ from 'User' table ]
            accounts =  user related account detail [ from 'Account' table ]
     """
    page = request.args.get('page', 1, type=int)
    users = User.query.paginate(page=page, per_page=3)
    accounts = Account.query.all()
    return render_template('admin_user_data.html', users=users, accounts=accounts)


@admin.route("/admin/delete-user/<user_id>/", methods=['GET', 'POST'])
@login_required
@authentication_req
def delete_user(user_id):
    """
        DELETE particular selected user and remove from the bank database
        template / redirects to: admin_user_data.html
    """
    User.query.filter_by(user_id=user_id).delete()
    db.session.commit()
    flash(USER_DELETED, FLASH_MESSAGES['SUCCESS'])
    return redirect(url_for('admin.admin_user_data'))


@admin.route("/admin/all-branch-data/", methods=['GET', 'POST'])
@login_required
@authentication_req
def admin_branch_data():
    """
        show all bank branches data
        templates/redirects to: admin_branch_data.html
        params:
            page = for pagination purpose
            per_page = number of rows shown in one-page
            branchs = all bank branch data [ from 'Branch' table ]
    """
    page = request.args.get('page', 1, type=int)
    branchs = Branch.query.order_by(Branch.branch_id.desc()).paginate(page=page, per_page=5)
    return render_template('admin_branch_data.html', branchs=branchs)


@admin.route("/admin/delete-branch-data/<int:branch_id>", methods=['GET', 'POST'])
@login_required
@authentication_req
def delete_branch_data(branch_id):
    """
        for delete particular bank branch
        if bank branch is associated / interlinked with any bank user then it will not delete
        else bank branch delete successfully
    """
    accounts = Account.query.all()
    branch_used = 0
    for account in accounts:
        if (account.branch_id) == (branch_id):
            branch_used += 1
    if branch_used == 0:
        branch = Branch.query.filter_by(branch_id=branch_id).first()
        db.session.delete(branch)
        db.session.commit()
        flash(BRANCH_DELETED, FLASH_MESSAGES['FAIL'])
    else:
        flash(BRANCH_IS_ASSOCIATED, FLASH_MESSAGES['FAIL'])
    return redirect(url_for('admin.admin_branch_data'))


@admin.route("/admin/all-atm-data/", methods=['GET', 'POST'])
@login_required
@authentication_req
def admin_atm_data():
    """
        show all bank branches data
        templates/redirects to: admin_branch_data.html
        params:
            page = for pagination purpose
            per_page = number of rows shown in one-page
            branchs = all bank branch data [ from 'Branch' table ]
    """
    page = request.args.get('page', 1, type=int)
    atms = Atm.query.order_by(Atm.atm_id.desc()).paginate(page=page, per_page=5)
    return render_template('admin_atm_data.html', atms=atms)


@admin.route("/admin/delete-atm-data/<atm_id>", methods=['GET', 'POST'])
@login_required
@authentication_req
def delete_atm_data(atm_id):
    """
        for delete particular bank atm
        if bank atm has the atm id then delete successfully
        params: particular atm's atm id
    """
    atm = Atm.query.filter_by(atm_id=atm_id).first()
    if atm:
        db.session.delete(atm)
        db.session.commit()
        flash(ATM_DELETED, FLASH_MESSAGES['SUCCESS'])
        return redirect(url_for('admin.admin_atm_data'))


@admin.route("/admin/all-loan-data/", methods=['GET', 'POST'])
@login_required
@authentication_req
def admin_user_loan_data():
    """
        shows the loan's data which is requested by the user
        included status [ Active / Inactive ]
    """
    page = request.args.get('page', 1, type=int)
    user = User.query.paginate(page=page, per_page=5)
    loans = Loan.query.all()
    loantype = LoanType.query.all()
    return render_template('admin_user_loan_data.html', loans=loans, loantype=loantype, user=user)


@admin.route("/admin/loan-approval-status/<user_id>/", methods=['GET', 'POST'])
@login_required
@authentication_req
def loan_approval(user_id):
    """
        admin can change the loan status data
        initially it will be Inactive [ by default ]
        two options for approval : [ 1.Active & 2.Inactive ]
    """
    user = User.query.filter_by(user_id=user_id).first()
    if user:
        loan = Loan.query.filter_by(user_id=user_id).first()
        if loan:
            loan_type = LoanType.query.filter_by(loan_id=loan.loan_id).first()
            form = LoanApprovalStatus()
            if form.validate_on_submit():
                approval_status = form.approval_status.data
                if approval_status == '1':
                    loan.loan_status = 'Active'
                    add_loan_money_to_user(user_id, loan.loan_amount, loan_type.loan_type)
                else:
                    loan.loan_status = 'Inactive'
                db.session.commit()
                flash(STATUS_UPDATE.format(user_name=user.user_name, activity='loan'), FLASH_MESSAGES['SUCCESS'])
                return redirect(url_for('admin.admin_user_loan_data'))
            elif request.method == 'GET':
                form.user_id.data = user_id
                form.user_name.data = user.user_name
                form.loan_id.data = loan.loan_id
                form.loan_amount.data = loan.loan_amount
                form.rate_interest.data = loan.rate_interest
                form.paid_amount.data = loan.paid_amount
                form.loan_type.data = loan_type.loan_type
                form.loan_status.data = loan.loan_status
        else:
            flash(NO_RECORD_ACTIVITY.format(activity='Loan'), FLASH_MESSAGES['FAIL'])
            return redirect(url_for('admin.admin_dashboard'))
    else:
        flash(NO_USER_FOUND.format(id=user_id), FLASH_MESSAGES['FAIL'])
        return redirect(url_for('admin.admin_dashboard'))

    return render_template(
        'loan_request_approval.html',
        user_id=user_id,
        user_name=user.user_name,
        loan_id=loan.loan_id,
        loan_amount=loan.loan_amount,
        rate_interest=loan.rate_interest,
        paid_amount=loan.paid_amount,
        loan_type=loan_type.loan_type,
        loan_status=loan.loan_status,
        title='account-status', form=form
    )

banking_system/templates/about.html
{% extends "base.html" %}
{% block content %}
<div class="about-section" style=" padding: 50px;
text-align: center;
background-color: rgb(25, 25, 53);
color: white;">
    <div class="row">
        <div class="col-md-4">
            <img src="{{url_for('static', filename='pics/sjk_logo.jpg')}}" alt="fttgh">
        </div>
        <div class=" col-md-8">
            <h1 style=" color:white ;">About Us Page</h1>
            <hr style="background-color: white;">
            <p>Hey this is SJK BANK!!!.</p>
            <p> Just do it....lets live fully...</p>
        </div>
    </div>
</div>
<br>
<h2 style="text-align:center">Our Team</h2>
<div class="row">
    {% for member in bank_member %}
    <div class="column" style=" float: left;width: 33.3%;margin-bottom: 16px;padding: 0 8px;">
        <div class="card" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);margin: 8px;">
            <img src="{{url_for('static', filename='pics/'+member.image_file)}}" alt="Picture"
                 style="width:100%; height: 250px;">
            <hr style="background-color:rgb(25, 25, 53);">
            <div class="container" style="padding: 0 16px;">
                <h2>{{member.bank_member_name}}</h2>
                {{member.bank_member_position}}
                <p class="title" style="color: grey;">{{member.bank_member_position}}</p>
                <p>{{member.bank_member_about}}</p>
                <p>{{member.bank_member_email_id}}</p>
                <p>
                    <button class="button" style="border: none;
					outline: 0;
					display: inline-block;
					padding: 8px;
					color: white;
					background-color: rgb(25, 25, 53);
					text-align: center;
					cursor: pointer;
					width: 100%;">Contact: {{member.bank_member_contact}}
                    </button>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

banking_system/templates/add_member_role_list.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add new bank member role</legend>
            <div class="form-group">
                {{ form.role_name.label(class="form-control-label")}}
                {% if form.role_name.errors %}
                {{ form.role_name(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.role_name.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.role_name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

banking_system/templates/admin_atm_data.html
{% extends "base.html" %}
{% block content %}
<a href="{{url_for('admin.admin_dashboard')}}">
    <button>Go back</button>
</a>
<br>
<hr>
<div class="col-md-4" style="text-align:center;border:solid;padding:15px;">
    <h5 style="text-align: center;;background:black;color:white;">bank atm's Data</h5>
    <table style="text-align:left">
        <tr>
            <th style="text-align:left">
                <pre>id     </pre>
            </th>&nbsp;
            <th style="text-align:left">
                <pre>atm address   </pre>
            </th>&nbsp;
            <th style="text-align:left"><pre>Wanna delete   </pre></th>
        </tr>
        {% for atm in atms.items %}
        <tr>
            <td>
                <pre>{{atm.atm_id}}   </pre>
            </td>&nbsp;
            <td>
                <pre>{{atm.atm_address}}   </pre>
            </td>&nbsp;
            <td><a href="{{url_for('admin.delete_atm_data',atm_id=atm.atm_id)}}">
                                    <button>Delete</button></a></td>&nbsp;
        </tr>
        {% endfor %}
    </table>
    {% for page_num in atms.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if atms.page == page_num %}
    <a href="{{ url_for('admin.admin_atm_data', page=page_num)}}">
        <button>{{page_num}}</button>
    </a>
    {% else %}

    <a href="{{ url_for('admin.admin_atm_data', page=page_num)}}">
        <button>{{page_num}}</button>
    </a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
    <hr>
    <a href="{{url_for('admin.add_atm')}}" style="text-align:left">
        <button>Add new Bank atm</button>
    </a>
</div>
{% endblock content %}

banking_system/templates/admin_login.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Admin Login</legend>
				<div class="form-group">
					{{ form.user_email.label(class="form-control-label")}}
					{% if form.user_email.errors %}
						{{ form.user_email(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.user_email.errors %}
							<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.user_email(class="form-control form-control-lg") }}
					{% endif %}		
				</div>
				<div class="form-group">
					{{ form.user_password.label(class="form-control-label")}}
					{% if form.user_password.errors %}
						{{ form.user_password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.user_password.errors %}
							<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.user_password(class="form-control form-control-lg") }}
					{% endif %}			
				</div>
				<div class="form-check">
					{{ form.remember(class="form-check-input")}}
					{{ form.remember.label(class="form-check-label")}}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
				<small class="text-muted ml-2">
					<a href="{{ url_for('users.reset_request') }}" style="color:black">Forgot Password??</a>
				</small>
			</div>
		</form>
	</div>
{% endblock content %}

banking_system/templates/admin_user_loan_data.html
{% extends "base.html" %}
{% block content %}
<a href="{{url_for('admin.admin_dashboard')}}"><button>Go back</button></a>
<br>
<hr>
<div class="row">
          <br>
            <br>
            <div class="col-md-12" style="text-align:center;border:solid;padding:15px;">
                <h5 style="text-align: center;background:black;color:white;">user's Loan Data</h5>
                <table style="text-align:left">
                    <tr>

                        <th style="text-align:left"><pre>User id     </pre></th>&nbsp;
                        <th style="text-align:left"><pre>User name  </pre></th>&nbsp;
                        <th style="text-align:left"><pre>Loan id   </pre></th>
                        <th style="text-align:left"><pre>Loan amount   </pre></th>
                        <th style="text-align:left"><pre>Rate interest   </pre></th>
                        <th style="text-align:left"><pre>Paid amount   </pre></th>
                        <th style="text-align:left"><pre>Loan Type   </pre></th>
                        <th style="text-align:left"><pre>Loan status   </pre></th>
                        <th style="text-align:left"><pre>Loan approval   </pre></th>

                    </tr>
                    {% for user in user.items %}
                    {% if user.user_email!='steffy.inexture@gmail.com' %}
                    <tr>

                        {% for loan in loans%}
                        {% if loan.user_id==user.user_id %}
                        {% for loantype in loantype %}
                        {% if loantype.loan_id==loan.loan_id %}
                        <td><pre>{{user.user_id}}   </pre></td>&nbsp;
                        <td><pre>{{user.user_name}}  </pre></td>&nbsp;
                        <td><pre>{{loan.loan_id}}  </pre></td>&nbsp;
                        <td><pre>{{loan.loan_amount}}  </pre></td>&nbsp;
                        <td><pre>{{loan.rate_interest}}  </pre></td>&nbsp;
                        <td><pre>{{loan.paid_amount}}  </pre></td>&nbsp;
                        <td><pre>{{loantype.loan_type}}  </pre></td>&nbsp;
                        <td><pre><button>{{loan.loan_status}}  </pre></button></td>&nbsp;
                        <td><pre><button><a href="{{url_for('admin.loan_approval',
                                                    user_id=user.user_id)}}">Aprroval status</a>  </pre></button></td>&nbsp;
                        {% endif %}
                        {% endfor %}

                        {% endif %}
                        {% endfor%}
                    </tr>
                    {%endif%}
                    {% endfor %}
                </table>

                {% for page_num in user.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)  %}
                            {% if page_num %}
                                {% if user.page == page_num %}
                <a href="{{ url_for('admin.admin_user_loan_data', page=page_num)}}"><button>{{page_num}}</button></a>
                                {% else %}

                <a href="{{ url_for('admin.admin_user_loan_data', page=page_num)}}"><button>{{page_num}}</button></a>
                                {% endif %}
                            {% else %}
                                ...
                            {% endif %}

                        {% endfor %}
                <hr>
                <a href="{{url_for('users.register')}}"><button>Add other loan for users</button></a>
            </div>
    </div>
{% endblock content %}

banking_system/templates/bank_statement.html
<!doctype html>
<html>
    <head>
    </head>

    <body>

<main role="main" class="container">
    <pre style="background-color: black; color:aliceblue; text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;Bank statements :</pre>
    </h4>
    <h4>Name: {{current_user.user_name}}</h4>
    <h4>Email: {{current_user.user_email}}</h4>
    <h4>Account number: {{account.account_number}}</h4>
    <table style="font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;">
                <tr style="border: 1px solid #dddddd;
                text-align: left;
                padding: 8px;">
                    <th style="border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;">Transaction id</th>
                    <th style="border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;">Transaction date</th>
                    <th style="border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;">Transaction amount</th>
                    <th style="border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;">Sender id</th>
                    <th style="border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;">Reciever id</th>
                    <th style="border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;">Transaction type</th>
                </tr>
                {% for transaction in transactions %}
                <tr style="border: 1px solid #dddddd;
                text-align: left;
                padding: 8px;">
                    <td style="border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;">{{transaction.transaction_id}}</td>
                    <td style="border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;">{{transaction.transaction_date}}</td>
                    <td style="border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;">{{transaction.transaction_amount}}</td>
                    <td style="border: 1px solid #dddddd;
                     text-align: left;
                     padding: 8px;">{{transaction.sender_id}}</td>
                    <td style="border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;">{{transaction.receiver_id}}</td>
                    {% for transaction_type in transaction_type %}
                    {%if transaction_type.transaction_id==transaction.transaction_id %}
                    <td style="border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;">{{transaction_type.transaction_type}}</td>
                    {%endif%}
                    {% endfor %}
                </tr>

                {% endfor %}
    <hr>

</main>

    </body>
</html>

banking_system/templates/change_branch.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Account status change</legend>
				<div class="form-group">
					{{ form.user_id.label(class="form-control-label")}}
					{% if form.user_id.errors %}
						{{ form.user_id(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.user_id.errors %}
							<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.user_id(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.user_name.label(class="form-control-label")}}
					{% if form.user_name.errors %}
						{{ form.user_name(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.user_name.errors %}
							<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.user_name(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.account_number.label(class="form-control-label")}}
					{% if form.account_number.errors %}
						{{ form.account_number(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.account_number.errors %}
							<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.account_number(class="form-control form-control-lg") }}
					{% endif %}
				</div>

				<div class="form-group">
					{{ form.myField.label(class="form-control-label")}}
					{% if form.myField.errors %}
						{{ form.myField(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.myField.errors %}
							<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.myField(class="form-control form-control-lg") }}
					{% endif %}
				</div>

			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
{% endblock content %}

banking_system/templates/fd.html
{% extends "base.html" %}
{% block content %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-12" style="background-color:rgb(39, 45, 83);color:white;padding:20px">
            About fixed deposits
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-md-6">
            <img src="{{url_for('static', filename='pics/fixed_deposit.png')}}" alt="fttgh" height="360px"
                width="500px">
        </div>
        <div class="col-md-6">
            <pre>
The 4 different types of money as classified by the economists 
are commercial money, fiduciary money, fiat money, commodity 
money.
Money whose value comes from a commodity of which it is made is 
known as commodity money. 
You can read about the Money Supply in Economy 
– Types of Money, Monetary Aggregates, Money Supply Control in 
the given link.

A government-issued currency that is not backed by 
a commodity such as gold is known as Fiat Money. 
Payment on the basis of trust but not on the basis of 
any order of the government is known as fiduciary money; 
examples are cheques. The portion of a currency which 
is made of book money 
– debt generated by commercial banks is known as commercial 
bank money.
            </pre>
        </div>
    </div>
</main>
{% endblock content %}

banking_system/templates/home.html
{% extends "base.html" %}
{% block content %}

<ul class="list-group">
	<li class="list-group-item"><img src="{{url_for('static', filename='pics/sjk_logo.jpg')}}" alt="fttgh"">
		&nbsp;&nbsp;&nbsp;Hey! Welcome to the SJK banking system
	</li>
</ul>

<br>
<br>
<ul class="list-group">
	<li class="list-group-item"><img src="{{url_for('static', filename='pics/money.png')}}" alt="fttgh" height="200px" width="400px">
		&nbsp;&nbsp;&nbsp;Your money will be safe with us &nbsp;&nbsp;&nbsp;<button type="button"><a href="{{ url_for('about.money') }}">About money</a></button> <br>
	</li>
</ul>
<br>
<br>
<ul class="list-group">
	<li class="list-group-item"><img src="{{url_for('static', filename='pics/fd.png')}}" alt="fttgh" height="200px" width="400px">
		&nbsp;&nbsp;&nbsp;Fixed deposites will be the safer option.&nbsp;&nbsp;&nbsp;<button type="button"><a href="{{ url_for('about.fd') }}">About fixed deposits</a></button> <br>
	</li>
</ul>
<br>
<br>
<ul class="list-group">
	<li class="list-group-item"><img src="{{url_for('static', filename='pics/loan.png')}}" alt="fttgh" height="200px" width="400px">
		&nbsp;&nbsp;&nbsp;No money?? no worries we are here for you! take loans :)&nbsp;&nbsp;&nbsp;<button type="button"><a href="{{ url_for('about.loan') }}">About loans</a></button> <br>
	</li>
</ul>
<br>
<br>
<ul class="list-group">
	<li class="list-group-item"><img src="{{url_for('static', filename='pics/insurance.png')}}" alt="fttgh" height="200px" width="400px">
		&nbsp;&nbsp;&nbsp;Your life is precious..take step towards insurance for better way!!&nbsp;&nbsp;&nbsp;<button type="button"><a href="{{ url_for('about.insurance') }}">About insurance</a></button> <br>
	</li>
</ul>

{% endblock content %}